CREATE DATABASE IF NOT EXISTS dines ;

CREATE TABLE dines(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(200) NOT NULL,
    score INT NOT NULL,
    restaurant VARCHAR(100) NOT NULL,
    address VARCHAR(200) NOT NULL,
    date DATE NOT NULL, 
    image VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);